Correction of the issue #146
nenes25/prestashop_console pull request #147
Opened 2020-09-16 09:43 UTC by m3uusi

Correction of the issue #146

The script can now correctly be executed from directories where no prestashop is installed in phar mode to install one.
In php mode, the script can only be executed from the directory where the console script is located :
This is necessary because prestashop path is searched with relative paths (../config/...)

This P.R. also contains the correction of the #142 because the code was required for this correction to be tested.

2020-09-21 06:53 UTC, nenes25 commented
@m3uusi  I have issue on the merge of the branch can you rebase your modifications on current dev branch ?

2020-09-21 06:54 UTC, nenes25 requested changes
Hi can you rebase on current dev branch ? I have some conflicts

2020-09-21 06:54 UTC, nenes25 commented on src/Hhennes/PrestashopConsole/Command/Module/ListCommand.php
>  class ListCommand extends Command
This command shoud not be in this pull request

2020-09-22 10:32 UTC, m3uusi commented
Branch merged with the current dev branch to resolve conflicts.

2020-09-22 11:48 UTC, nenes25 approved these changes
Sounds great thanks !

2020-09-22 11:48 UTC, merged